### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by arnefloh-biz** [radiant-rstats/radiant#161]
I was not able to install and load the radiant package. I received the following error message:

> library(radiant.data)
Error: package or namespace load failed for ‘radiant.data’ in namespaceExport(ns, exports):
 undefined exports: base64encode, base64decode, dataURI, checkUTF8

I'm using Win10/R4.1.0/R Studio 1.4.1717

Any help is appreciated.

Thanks, Arne

**Comment by vnijs** [comment]
I have the same set up and Radiant works fine. Did you use the all-in-one installer for Radiant? See install instructions below

https://radiant-rstats.github.io/docs/install.html

R may be trying to install into Documents otherwise and maybe Documents is in OneDrive. See the stackoverflow comment below.

https://stackoverflow.com/a/64004474/1974918

**Comment by vnijs** [comment]
Closing. Reopen as needed.
