### ISSUE TITLE
Error when visualizing

### ISSUE THREAD

**Issue by Dorothy44** [radiant-rstats/radiant#193]
Hi,

There is an error message:'mark_html' is not an exported object from 'namespace:markdown', when I clicked on Visualize tab.

![Screenshot 2022-12-21 090526](https://user-images.githubusercontent.com/121140548/208796667-5b7fee5f-74bc-484a-afeb-ddc60ab2dbbb.png)

Greatly appreciate any advice on this issue. Thank you.

**Comment by vnijs** [comment]
I ran into this same issue yesterday. The error is due to a change in the `knitr` package. For some reason you are getting the latest version of `knitr` but the install didn't upgrade the `markdown` package to 1.3 and so the `mark_html` function from that package is not (yet) available.

A quick fix would be to install the latest version of the `markdown` package:

`install.packages("markdown")`

Then restart Radiant

@yihui Any idea why `markdown` might not be getting updated to the correct version? On CRAN it looks like the requirements are set to `markdown>=1.3` which looks right

**Comment by yihui** [comment]
Unfortunately, versions of soft package dependencies can't be enforced, and **markdown** is only a soft dependency of **knitr**: https://github.com/yihui/knitr/blob/ea3990dc56ead69c9982a443550443762774e40e/DESCRIPTION#L125-L126 Installing a new version of **knitr** won't install the latest version of **markdown** automatically.

My general advice is [when in doubt, try to update software packages.](https://yihui.org/en/2017/05/when-in-doubt-upgrade/)

**Comment by Dorothy44** [comment]
Dear all,

Thanks a lot for looking into the issue and your advice.

Wishing all a Merry Christmas and Happy New Year in advance. 😊


Best regards,
Dorothy

________________________________

**Comment by vnijs** [comment]
Thanks for the explanation @yihui and thanks for reporting the issue @Dorothy44. I will add a hard dependency on the `markdown >= 1.3` in the next release of the radiant packages. In the meantime, users will have to upgrade the `markdown` package manually using the command below.

```
install.packages("markdown")
```
