### ISSUE TITLE
Issue in the new mac version

### ISSUE THREAD

**Issue by sjennings6** [radiant-rstats/radiant#52]
When running a linear regression model on the new version, the values for the +/- column are 1/3 what they were in the previous version.

<img width="1139" alt="screen shot 2018-04-05 at 11 07 36 am" src="https://user-images.githubusercontent.com/31108135/38374450-a6c1220a-38c1-11e8-9c3f-6f7894a0cf33.png">

**Comment by vnijs** [comment]
See https://github.com/radiant-rstats/radiant.model/blob/master/NEWS.md
`Default interval for predictions from a linear regression is now "confidence" rather than "prediction"`

For consistency with _Model > Logistic_ the default interval type for prediction is now "confidence". So you are seeing confidence intervals rather than the previously used prediction intervals.

To produce prediction intervals add the "interval = 'prediction'" argument to the call to `predict` after you click the report icon in _Report > Rmd_. See example below. In R(studio) use `?radiant.model::predict.regress` for documentation

```{r}
result <- regress(
  dataset = "diamonds", 
  rvar = "price", 
  evar = c("carat", "clarity")
)
summary(result)
pred <- predict(result, pred_data = "diamonds")
print(pred, n = 10)
```

```{r}
pred <- predict(result, pred_data = "diamonds", interval = "prediction")
print(pred, n = 10)
```

## Output
<pre>
Linear regression (OLS)
Data     : diamonds 
Response variable    : price 
Explanatory variables: carat, clarity 
Null hyp.: the effect of x on price is zero
Alt. hyp.: the effect of x on price is not zero

              coefficient std.error t.value p.value    
 (Intercept)    -6780.993   204.952 -33.086  < .001 ***
 carat           8438.030    51.101 165.125  < .001 ***
 clarity|SI2     2790.760   201.395  13.857  < .001 ***
 clarity|SI1     3608.531   200.508  17.997  < .001 ***
 clarity|VS2     4249.906   201.607  21.080  < .001 ***
 clarity|VS1     4461.956   204.592  21.809  < .001 ***
 clarity|VVS2    5109.476   210.207  24.307  < .001 ***
 clarity|VVS1    5027.669   214.251  23.466  < .001 ***
 clarity|IF      5265.170   233.658  22.534  < .001 ***

Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

R-squared: 0.904,  Adjusted R-squared: 0.904 
F-statistic: 3530.024 df(8,2991), p.value < .001
Nr obs: 3,000 

Linear regression (OLS)
Data                 : diamonds 
Response variable    : price 
Explanatory variables: carat, clarity 
Prediction dataset   : diamonds 
Rows shown           : 10 of 3,000 

 carat clarity Prediction     2.5%    97.5%     +/-
 0.320     VS1    381.133  259.827  502.440 121.306
 0.340     SI1   -303.531 -406.617 -200.445 103.086
 0.300     VS2      0.322 -103.626  104.270 103.948
 0.350    VVS2   1281.793 1137.055 1426.532 144.738
 0.400     VS2    844.125  744.145  944.105  99.980
 0.600    VVS1   3309.494 3148.640 3470.349 160.854
 0.880     SI1   4253.005 4163.416 4342.594  89.589
 0.930     SI1   4674.907 4585.009 4764.804  89.897
 0.510    VVS2   2631.878 2488.968 2774.789 142.910
 1.010     SI2   4532.177 4427.428 4636.926 104.749

Linear regression (OLS)
Data                 : diamonds 
Response variable    : price 
Explanatory variables: carat, clarity 
Prediction dataset   : diamonds 
Rows shown           : 10 of 3,000 

 carat clarity Prediction      2.5%    97.5%      +/-
 0.320     VS1    381.133 -2026.147 2788.413 2407.280
 0.340     SI1   -303.531 -2709.962 2102.900 2406.431
 0.300     VS2      0.322 -2406.146 2406.790 2406.468
 0.350    VVS2   1281.793 -1126.782 3690.368 2408.575
 0.400     VS2    844.125 -1562.175 3250.425 2406.300
 0.600    VVS1   3309.494   899.897 5719.091 2409.597
 0.880     SI1   4253.005  1847.115 6658.896 2405.891
 0.930     SI1   4674.907  2269.005 7080.809 2405.902
 0.510    VVS2   2631.878   223.412 5040.344 2408.466
 1.010     SI2   4532.177  2125.674 6938.680 2406.503
</pre>

**Comment by vnijs** [comment]
@sjennings6 In the next release you will see the interval type used for linear regression mentioned explicitly in the output as shown below.

<pre>
Linear regression (OLS)
Data                 : diamonds 
Response variable    : price 
Explanatory variables: carat, clarity 
Interval             : confidence 
Prediction dataset   : diamonds 
Rows shown           : 10 of 3,000 

 carat clarity Prediction     2.5%    97.5%     +/-
 0.320     VS1    381.133  259.827  502.440 121.306
 0.340     SI1   -303.531 -406.617 -200.445 103.086
 0.300     VS2      0.322 -103.626  104.270 103.948
 0.350    VVS2   1281.793 1137.055 1426.532 144.738
 0.400     VS2    844.125  744.145  944.105  99.980
 0.600    VVS1   3309.494 3148.640 3470.349 160.854
 0.880     SI1   4253.005 4163.416 4342.594  89.589
 0.930     SI1   4674.907 4585.009 4764.804  89.897
 0.510    VVS2   2631.878 2488.968 2774.789 142.910
 1.010     SI2   4532.177 4427.428 4636.926 104.749
Linear regression (OLS)
Data                 : diamonds 
Response variable    : price 
Explanatory variables: carat, clarity 
Interval             : prediction 
Prediction dataset   : diamonds 
Rows shown           : 10 of 3,000 

 carat clarity Prediction      2.5%    97.5%      +/-
 0.320     VS1    381.133 -2026.147 2788.413 2407.280
 0.340     SI1   -303.531 -2709.962 2102.900 2406.431
 0.300     VS2      0.322 -2406.146 2406.790 2406.468
 0.350    VVS2   1281.793 -1126.782 3690.368 2408.575
 0.400     VS2    844.125 -1562.175 3250.425 2406.300
 0.600    VVS1   3309.494   899.897 5719.091 2409.597
 0.880     SI1   4253.005  1847.115 6658.896 2405.891
 0.930     SI1   4674.907  2269.005 7080.809 2405.902
 0.510    VVS2   2631.878   223.412 5040.344 2408.466
 1.010     SI2   4532.177  2125.674 6938.680 2406.503
</pre>

**Comment by sjennings6** [comment]
Thank you so much for the clarification.
