### ISSUE TITLE
update and functions

### ISSUE THREAD

**Issue by Marie-Ann-S** [radiant-rstats/radiant#62]
Hi,

I am using radiant for my stats class (the GUI as well as the functions that are generated by the GUI). Unforunately I allways need a new installation of radiant for each class, because the computers in the PC pool do not allow a permanent installation. Currently, with the release of the latest radiant version, the functions of the previous version do not work anymore.  I tried to install an old release of radiant from CRAN (i.e., radiant_0.8.0.tar.gz ), but this does not fix the problem. Is there a way that allows me to use the old syntax of the last radiant version (because changing all skipts in the middle of class will be difficult)?

Best Marie-Ann

**Comment by vnijs** [comment]
Sorry to hear that @Marie-Ann-S. Radiant 0.9.5 is indeed a major release with some breaking changes. The easiest way to "fix" old code is to run it in Report > Rmd or Report > R in the new version. When you click the Knit button you should see a popup asking if you want to update the code. This should solve most problems automatically. If you have any state files that aren't fixed by this approach feel free to email them to me @ radiant@rady.ucsd.edu and I will take a look.

One way to use the old version would be to get all the source packages for radiant.data, radiant.design, radiant.basics, radiant.model, radiant.multivariate, and radiant and install those. Alternatively, you could try https://mran.microsoft.com/documents/rro/reproducibility. I haven't used this myself but I think it should work with "regular" R as well.

**Comment by Marie-Ann-S** [comment]
Thank you for you fast answer Vincent,

Your suggestions helped me a lot. The checkpoint package from the reproducibility website runs with regluar R. It is a bit lazy, but allows to use all previous versions of the packages by specifying a specific time point. This add on to my skripts is, at present, the most convienient strategy, because the actual R Studio version is not available in the PC lab, as well and that leads to problems for starting the GUI with the new version.

Best, Marie-Ann

**Comment by vnijs** [comment]
Thanks for the update @Marie-Ann-S. I hope you can get some R tools (permanently) installed in the PC pool in the future. If you have any trouble upgrading scripts to the new version of radiant let me know  in a new issue.
