### ISSUE TITLE
If headers have spaces or apostrophes, put them in quotation marks when code is created

### ISSUE THREAD

**Issue by josh1400** [radiant-rstats/radiant#74]
**Ignore**: Listen to second comment

When CSVs are loaded, spaces and apostrophes should be changed to underscores automatically.

This would prevent errors when creating an automated report.  I can change the names of these headers in the Transform tab, but when I put the code in my report I get errors.  For example, the following code creates Error: <text>:2:84: unexpected symbol because of the space in DP Entity.

```{r}
## Load commands
ASA_Disti_Focus <- readr::read_csv("C:/Users/jdaulton/Desktop/Algorithms/Biz ops/Allocation Algorithm/Input Files/ASA/ASA_Focus_Q2_Q3.csv", n_max = Inf) %>%
  to_fct()
register("ASA_Disti_Focus")
```

```{r}
## rename variable(s)
ASA_Disti_Focus <- rename(ASA_Disti_Focus, dp_entity = DP Entity, dp_division = DP Division, market_subsegment = Segment, focus_account = Focus Account, design_id = Design ID, part_number = MPN, Q2_focus_forecast = Q2'19 Forecast, Q3_focus_forecast = Q3'19 Forecast)
```

**Comment by josh1400** [comment]
**Easier/Preferred solution:** Make the transform tab include quotation marks in the code when a header that has a space or apostrophe is renamed.  This would probably also be applicable to all code that's created.

**Comment by josh1400** [comment]
Example of solution:

```{r}
## rename variable(s)
ASA_Disti_Focus <- rename(ASA_Disti_Focus, dp_entity = "DP Entity", dp_division = "DP Division", market_subsegment = Segment, focus_account = "Focus Account", design_id = "Design ID", part_number = MPN, Q2_focus_forecast = "Q2'19 Forecast", Q3_focus_forecast = "Q3'19 Forecast")
```

**Comment by vnijs** [comment]
I updated a few functions so that `fix_names` is applied automatically for csv files. That way you do not have to `rename` using _Data > Transform_. If you have the appropriate development tools you can install the update using the command below. Else, it will be available in the next release (probably next week).

Thanks for reporting @josh1400!

`devtools::install_github("radiant-rstats/radiant.data")`

**Comment by josh1400** [comment]
Just ran an update and this wasn't done.  Have you not pushed out the update yet?

**Comment by vnijs** [comment]
I did push the changes, although `fix_names` is not yet automatically added to `Read files` in _Report > Rmd_. In what setting are you seeing an issue?

**Comment by vnijs** [comment]
Updates pushed last night to add fix_names for `Read files` in _Report > Rmd_. Please reopen of you still have an issue

**Comment by DataStrategist** [comment]
Found one. In the pivotr menu going to knitr

![image](https://user-images.githubusercontent.com/8094091/47012161-7d48d180-d13b-11e8-901a-32eff049551d.png)

**Comment by vnijs** [comment]
@DataStrategist This issue was actually about variables names with spaces. Your example is about a dataset with spaces in the name. Radiant *should* actually fix the data name automatically when you load it. See example below where the file loaded was `click with spaces.rda`. Can you provide more information about the file you loaded (e.g., what type: csv, rda, etc) and how you got it into radiant?

```{r}
click_with_spaces <- readr::read_rds("/Users/vnijs/Desktop/click with spaces.rds")
register("click_with_spaces")
```

```{r}
result <- pivotr(
  click_with_spaces, 
  cvars = "wholesaler_eff", 
  nr = 4
)
summary(result)
# dtab(result) %>% render()
```

**Comment by vnijs** [comment]
See screenshot below from the _Data > Manage_ tab. What version of Radiant are you using?

To ensure you have the latest version use:

```
install.packages("radiant.update", repos = "https://radiant-rstats.github.io/minicran/")
radiant.update::radiant.update()
```

![image](https://user-images.githubusercontent.com/2998956/47103069-3e765280-d1f3-11e8-8961-6eec6201a1a3.png)

**Comment by DataStrategist** [comment]
Yep, that did the trick! Because I had some issues getting it installed for "ALL USERS" (including the shiny one, I post the code that works from Terminal, would this be beneficial in any place of the documentation?

`sudo su - -c \\"R -e \"install.packages('radiant.update', repos = 'https://radiant-rstats.github.io/minicran/')\"\\"`

**Comment by vnijs** [comment]
Added it to the install page. Thanks for the suggestion @DataStrategist
